logLevel: debug
sever:
  # name of the “kube-killer” server deployment
  name: kube-killer
  # namespace of the “kube-killer” server
  namespace: kube-system
  logLevel: debug
database:
  mysql:
    # If the db does not exist.It will create the db automatically
    # +optional,the default value would be “kube_killer”.
    db: kube_killer
    # If the table does not exist.It will create the table automatically
    tables: 
      - terminator
    host: www.bullshitprogram.com:3306
    user: root
    pwd: root